### ISSUE TITLE
Recent upgrades to Spotlight

### ISSUE THREAD

**Issue by KnowledgeGarden** [MartinoMensio/spacy-dbpedia-spotlight#19]
the DBpedia Spotlight repo says it's not in active development anymore. The root website does say that the cloud servers remain active.
Spotlight migrated to DBpedia Model, a different repo, which is in continuous upgrade.
What's not clear to me is whether the cloud servers moved to Model and are current with their data.
I found in my own work that it was faster to download Spotlight and drop it on a local server, then switched that to the Model code and data. What is encouraging - without any solid evidence is that the model repo

https://github.com/dbpedia-spotlight/dbpedia-spotlight-model

references the spotlight website as its home. Fair chance the data is up to date.

As a former KMI member, I take great interest in this project and your work.

**Comment by MartinoMensio** [comment]
Hi Jack @KnowledgeGarden ,
Thank you very much for opening this issue. Before today, I wasn't sure whether these models were the most updated, but thanks to your issue and the info you provided, I did some investigation and testing.

By doing some investigation, I can confirm that:
- the dbpedia-spotlight API publicly available at https://api.dbpedia-spotlight.org/{LANGUAGE}/ and documented at https://www.dbpedia-spotlight.org/api is updated with recent models (hopefully the last one). This is confirmed by all the pointers in the dbpedia-spotlight-model repository, and also by the availability of further languages that just became available with v1.0+
- The latest models are kept up to date (2022_03_01), and are published at https://databus.dbpedia.org/dbpedia/spotlight/spotlight-model/
- This wrapper library for spaCy therefore is connected to the latest models if used with the public endpoints
- The instructions to deploy locally have been updated to download and use the latest models (2022_03_01) and code (dbpedia-spotlight version 1.1) so that even the local execution is up to date.

I'm very satisfied with this fruitful KMi interaction!

Best,
Martino
